resource_types:
- name: terraform
  type: docker-image
  source:
    repository: ljfranklin/terraform-resource
    tag: beta-backend

resources:

- name: env-state-aws
  type: terraform
  source:
    env_name: ((env_name))
    backend_type: s3
    backend_config:
      bucket: platform-automation-terraform
      key: pks-on-aws/terraform.tfstate
      region: us-east-1
      access_key: ((access_key))
      secret_key: ((secret_key))
    vars:
      region: ((region))
      env_name: ((env_name))
      ops_manager_ami: ((ops_manager_ami))
      access_key: ((access_key))
      secret_key: ((secret_key))
      ssl_cert: ((ssl_cert))
      ssl_private_key: ((ssl_private_key))
      availability_zones: ((availability_zones))
      rds_instance_count: ((rds_instance_count))
      dns_suffix: ((dns_suffix))
      vpc_cidr: ((vpc_cidr))
    env:
      AWS_ACCESS_KEY_ID: ((access_key))
      AWS_SECRET_ACCESS_KEY: ((secret_key))

jobs:
- name: destroy-terraform
  plan:
  - put: env-state-aws
    params:
      env_name: ((env_name))
      action: destroy
    get_params:
      action: destroy
